### ISSUE TITLE
Prettify query output

### ISSUE THREAD

**Issue by Bluesir9** [murer/dsopz#9]
Currently when running a query, the output comes out as a wall of text which is not easy to read through especially if the number of fields are large. I was wondering if we could print the output like you get in case of a PostgreSQL/MySQL db. The name of the fields would be printed in the first row and the values would then follow in separate rows. It would help in improving readability and will look more familiar to people coming from SQL background.

I have just started looking at the repo and I believe the necessary changes need to be made in the console.py file. 

If the idea sounds good to you then I would like to proceed with making the necessary changes.

**Comment by murer** [comment]
That sounds great. And I believe you are right about console.py.
Thanks in advance

**Comment by murer** [comment]
Time out
